### PR TITLE
Show results without input

### LINKED ISSUE #62: Suggestions on start
Hi @PhiloNL , I got some ideas I hope you find them interesting 

1. Function suggestion on open (some people prefer clicking than typing), this could be used to show for example: latest visited pages , last search or last used function 
2. Be able to search on open (from the start), for example: show results of clients and invoices (keeping functions on the top)

Thanks for the package

### PR DESCRIPTION
**Pull request by riasvdv**
This PR makes it so the results are shown even without any search input. Closes #62 

image

I feel like it's a better default command palette behaviour, we could still put this behind a config flag if you prefer?

### CODE REVIEW

**Comment by PhiloNL** [comment]
Thanks for the PR. Given it changes the default behavior people are currently expecting I would prefer having a config flag. In the next major version, it can be set to true on default.

**Comment by riasvdv** [comment]
@PhiloNL Added a config setting for it that defaults to `false`!

**Comment by PhiloNL** [comment]
Thanks @riasvdv 🙌

**Comment by danpalmieri** [comment]
It is tagged?

**Comment by undjike** [comment]
Hello, there is a display issue with this parameter set to true.

The problem occurs when the command uses more than one dependency.

The results displayed by the first search affect the display of the second search.

**Pull request merged**
